[server]
listen = "127.0.0.1:9999"
ssl = true
cert_path = "/etc/ptm/cert.pem"
key_path = "/etc/ptm/key.pem"

[[location]]
name = "ssh"
path = "/ssh"
forward_to = "127.0.0.1:40000"

[[location]]
name = "api"
path = "/api"
forward_to = "127.0.0.1:5000"

[[location]]
name = "db"
path = "/db"
forward_to = "mysql:3306"
