[server]
listen = "127.0.0.1:40001"
ssl = true
cert_path = "cert.pem"
key_path = "key.pem"

[[location]]
name = "ssh"
path = "/ssh"
forward_to = "127.0.0.1:40000"

[[location]]
name = "web"
path = "/"
forward_to = "127.0.0.1:7722"

[[location]]
name = "graphql"
path = "/graphql"
forward_to = "127.0.0.1:8080/graphql"
