[server]
listen = "127.0.0.1:9999"
ssl = true
cert_path = "cert.pem"
key_path = "key.pem"

[[location]]
name = "web"
path = "/"
forward_to = "127.0.0.1:7722"

[[location]]
name = "ssh"
path = "/ssh"
forward_to = "127.0.0.1:22"

[[location]]
name = "api"
path = "/api"
forward_to = "http://127.0.0.1:5000/api"
